version: '2'
services:
  phalcon:
    build:
      context: ./docker/phalcon
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./phalcon-app:/var/www/phalcon/
    links:
      - db:db
    networks:
      - phalcon-network
  db:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./phalcon-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: phalcon
      MYSQL_ROOT_PASSWORD: root
    networks:
      - phalcon-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
    restart: always
    ports:
        - 8890:80
    links:
        - db
    networks:
      - phalcon-network

networks:
  phalcon-network:
      driver: bridge
